apiVersion: v1
kind: Service
metadata:
  name: duanzh-service
  labels:
    app: duanzh
spec:
  selector:
    app: duanzh
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer